//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSCC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSCC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string _________ {
            get {
                return ResourceManager.GetString("_________", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string CreateItem_Amount {
            get {
                return ResourceManager.GetString("CreateItem_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string CreateItem_Cost {
            get {
                return ResourceManager.GetString("CreateItem_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CreateItem_Description {
            get {
                return ResourceManager.GetString("CreateItem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarity.
        /// </summary>
        public static string CreateItem_Rarity {
            get {
                return ResourceManager.GetString("CreateItem_Rarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string CreateItem_Rarity_Common {
            get {
                return ResourceManager.GetString("CreateItem_Rarity_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary.
        /// </summary>
        public static string CreateItem_Rarity_Legendary {
            get {
                return ResourceManager.GetString("CreateItem_Rarity_Legendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        public static string CreateItem_Rarity_Rare {
            get {
                return ResourceManager.GetString("CreateItem_Rarity_Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        public static string CreateItem_Rarity_Trash {
            get {
                return ResourceManager.GetString("CreateItem_Rarity_Trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommon.
        /// </summary>
        public static string CreateItem_Rarity_Uncommon {
            get {
                return ResourceManager.GetString("CreateItem_Rarity_Uncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string CreateItem_Rarity_Unique {
            get {
                return ResourceManager.GetString("CreateItem_Rarity_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Rare.
        /// </summary>
        public static string CreateItem_Rarity_VeryRare {
            get {
                return ResourceManager.GetString("CreateItem_Rarity_VeryRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wondrous.
        /// </summary>
        public static string CreateItem_Rarity_Wondrous {
            get {
                return ResourceManager.GetString("CreateItem_Rarity_Wondrous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string CreateItem_Type {
            get {
                return ResourceManager.GetString("CreateItem_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo.
        /// </summary>
        public static string CreateItem_Type_Ammo {
            get {
                return ResourceManager.GetString("CreateItem_Type_Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcane.
        /// </summary>
        public static string CreateItem_Type_Arcane {
            get {
                return ResourceManager.GetString("CreateItem_Type_Arcane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        public static string CreateItem_Type_Armor {
            get {
                return ResourceManager.GetString("CreateItem_Type_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string CreateItem_Type_Food {
            get {
                return ResourceManager.GetString("CreateItem_Type_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string CreateItem_Type_Other {
            get {
                return ResourceManager.GetString("CreateItem_Type_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potion.
        /// </summary>
        public static string CreateItem_Type_Potion {
            get {
                return ResourceManager.GetString("CreateItem_Type_Potion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest.
        /// </summary>
        public static string CreateItem_Type_Quest {
            get {
                return ResourceManager.GetString("CreateItem_Type_Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        public static string CreateItem_Type_Tool {
            get {
                return ResourceManager.GetString("CreateItem_Type_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trinket.
        /// </summary>
        public static string CreateItem_Type_Trinket {
            get {
                return ResourceManager.GetString("CreateItem_Type_Trinket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon.
        /// </summary>
        public static string CreateItem_Type_Weapon {
            get {
                return ResourceManager.GetString("CreateItem_Type_Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string CreateItem_Weight {
            get {
                return ResourceManager.GetString("CreateItem_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast Time.
        /// </summary>
        public static string CreateSpell_CastTime {
            get {
                return ResourceManager.GetString("CreateSpell_CastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration.
        /// </summary>
        public static string CreateSpell_Concentration {
            get {
                return ResourceManager.GetString("CreateSpell_Concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CreateSpell_Desc {
            get {
                return ResourceManager.GetString("CreateSpell_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string CreateSpell_Duration {
            get {
                return ResourceManager.GetString("CreateSpell_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string CreateSpell_Level {
            get {
                return ResourceManager.GetString("CreateSpell_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string CreateSpell_Material {
            get {
                return ResourceManager.GetString("CreateSpell_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string CreateSpell_Range {
            get {
                return ResourceManager.GetString("CreateSpell_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ritual.
        /// </summary>
        public static string CreateSpell_Ritual {
            get {
                return ResourceManager.GetString("CreateSpell_Ritual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        public static string CreateSpell_School {
            get {
                return ResourceManager.GetString("CreateSpell_School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string CreateSpell_ShortDesc {
            get {
                return ResourceManager.GetString("CreateSpell_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somatic.
        /// </summary>
        public static string CreateSpell_Somatic {
            get {
                return ResourceManager.GetString("CreateSpell_Somatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets.
        /// </summary>
        public static string CreateSpell_Targets {
            get {
                return ResourceManager.GetString("CreateSpell_Targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbal.
        /// </summary>
        public static string CreateSpell_Verbal {
            get {
                return ResourceManager.GetString("CreateSpell_Verbal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;Description&quot;: &quot;&quot;,
        ///        &quot;Name&quot;: &quot;Abacus&quot;,
        ///        &quot;Subtitle&quot;: &quot;adventuring gear&quot;,
        ///        &quot;Category&quot;: &quot;Items&quot;,
        ///        &quot;Weight&quot;: &quot;2&quot;
        ///    },
        ///    {
        ///        &quot;Description&quot;: &quot;As an action, you can splash the contents of this vial onto a creature within 5 feet of you or throw the vial up to 20 feet, shattering it on impact. In either case, make a ranged Attack against a creature or object, treating the acid as an improvised weapon. On a hit, the target takes 2d6 acid damage&quot;,
        ///        &quot;Name&quot;: &quot;A [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dnd5eitemindex {
            get {
                return ResourceManager.GetString("dnd5eitemindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;Abi-Dalzim&apos;s Horrid Wilting&quot;,
        ///    &quot;id&quot;: &quot;abi-dalzims_horrid_wilting&quot;,
        ///    &quot;Level&quot;: 8,
        ///    &quot;School&quot;: &quot;Necromancy&quot;,
        ///    &quot;CastingTime&quot;: &quot;1 Action&quot;,
        ///    &quot;Ritual&quot;: false,
        ///    &quot;Concentration&quot;: false,
        ///    &quot;Source&quot;: &quot;Elemental Evil&quot;,
        ///    &quot;Range&quot;: &quot;150 feet&quot;,
        ///    &quot;Components&quot;: &quot;V S M &quot;,
        ///    &quot;Duration&quot;: &quot;Instantaneous&quot;,
        ///    &quot;Description&quot;: &quot;You draw the moisture from every creature in a 30-foot cube centered on a point you choose within range. Each creature in that area must make a Constitution savi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dnd5espellindex {
            get {
                return ResourceManager.GetString("dnd5espellindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Edit_Languages {
            get {
                return ResourceManager.GetString("Edit_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance and Bio.
        /// </summary>
        public static string Extras_AaB {
            get {
                return ResourceManager.GetString("Extras_AaB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Extras_Age {
            get {
                return ResourceManager.GetString("Extras_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Extras_Appearance {
            get {
                return ResourceManager.GetString("Extras_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string Extras_Bio {
            get {
                return ResourceManager.GetString("Extras_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        public static string Extras_Extra {
            get {
                return ResourceManager.GetString("Extras_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        public static string Extras_Extras {
            get {
                return ResourceManager.GetString("Extras_Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feats.
        /// </summary>
        public static string Extras_Feats {
            get {
                return ResourceManager.GetString("Extras_Feats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Extras_Gender {
            get {
                return ResourceManager.GetString("Extras_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Extras_Height {
            get {
                return ResourceManager.GetString("Extras_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traits.
        /// </summary>
        public static string Extras_Traits {
            get {
                return ResourceManager.GetString("Extras_Traits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Extras_Weight {
            get {
                return ResourceManager.GetString("Extras_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Class.
        /// </summary>
        public static string General_AC {
            get {
                return ResourceManager.GetString("General_AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string General_Alignment {
            get {
                return ResourceManager.GetString("General_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE.
        /// </summary>
        public static string General_Alignment_CE {
            get {
                return ResourceManager.GetString("General_Alignment_CE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CG.
        /// </summary>
        public static string General_Alignment_CG {
            get {
                return ResourceManager.GetString("General_Alignment_CG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN.
        /// </summary>
        public static string General_Alignment_CN {
            get {
                return ResourceManager.GetString("General_Alignment_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE.
        /// </summary>
        public static string General_Alignment_LE {
            get {
                return ResourceManager.GetString("General_Alignment_LE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LG.
        /// </summary>
        public static string General_Alignment_LG {
            get {
                return ResourceManager.GetString("General_Alignment_LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LN.
        /// </summary>
        public static string General_Alignment_LN {
            get {
                return ResourceManager.GetString("General_Alignment_LN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        public static string General_Alignment_NE {
            get {
                return ResourceManager.GetString("General_Alignment_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG.
        /// </summary>
        public static string General_Alignment_NG {
            get {
                return ResourceManager.GetString("General_Alignment_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TN.
        /// </summary>
        public static string General_Alignment_TN {
            get {
                return ResourceManager.GetString("General_Alignment_TN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string General_Background {
            get {
                return ResourceManager.GetString("General_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acolyte.
        /// </summary>
        public static string General_Background_Acolyte {
            get {
                return ResourceManager.GetString("General_Background_Acolyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charlatan.
        /// </summary>
        public static string General_Background_Charlatan {
            get {
                return ResourceManager.GetString("General_Background_Charlatan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criminal.
        /// </summary>
        public static string General_Background_Criminal {
            get {
                return ResourceManager.GetString("General_Background_Criminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string General_Background_Custom {
            get {
                return ResourceManager.GetString("General_Background_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainer.
        /// </summary>
        public static string General_Background_Entertainer {
            get {
                return ResourceManager.GetString("General_Background_Entertainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folk Hero.
        /// </summary>
        public static string General_Background_FolkHero {
            get {
                return ResourceManager.GetString("General_Background_FolkHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild Artisan.
        /// </summary>
        public static string General_Background_GuildArtisan {
            get {
                return ResourceManager.GetString("General_Background_GuildArtisan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hermit.
        /// </summary>
        public static string General_Background_Hermit {
            get {
                return ResourceManager.GetString("General_Background_Hermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noble.
        /// </summary>
        public static string General_Background_Noble {
            get {
                return ResourceManager.GetString("General_Background_Noble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlander.
        /// </summary>
        public static string General_Background_Outlander {
            get {
                return ResourceManager.GetString("General_Background_Outlander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage.
        /// </summary>
        public static string General_Background_Sage {
            get {
                return ResourceManager.GetString("General_Background_Sage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sailor.
        /// </summary>
        public static string General_Background_Sailor {
            get {
                return ResourceManager.GetString("General_Background_Sailor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldier.
        /// </summary>
        public static string General_Background_Soldier {
            get {
                return ResourceManager.GetString("General_Background_Soldier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urchin.
        /// </summary>
        public static string General_Background_Urchin {
            get {
                return ResourceManager.GetString("General_Background_Urchin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonds.
        /// </summary>
        public static string General_Bonds {
            get {
                return ResourceManager.GetString("General_Bonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cha.
        /// </summary>
        public static string General_Cha {
            get {
                return ResourceManager.GetString("General_Cha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Name.
        /// </summary>
        public static string General_CharacterName {
            get {
                return ResourceManager.GetString("General_CharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma.
        /// </summary>
        public static string General_Charisma {
            get {
                return ResourceManager.GetString("General_Charisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbarian.
        /// </summary>
        public static string General_Class_Barbarian {
            get {
                return ResourceManager.GetString("General_Class_Barbarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bard.
        /// </summary>
        public static string General_Class_Bard {
            get {
                return ResourceManager.GetString("General_Class_Bard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleric.
        /// </summary>
        public static string General_Class_Cleric {
            get {
                return ResourceManager.GetString("General_Class_Cleric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druid.
        /// </summary>
        public static string General_Class_Druid {
            get {
                return ResourceManager.GetString("General_Class_Druid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter.
        /// </summary>
        public static string General_Class_Fighter {
            get {
                return ResourceManager.GetString("General_Class_Fighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monk.
        /// </summary>
        public static string General_Class_Monk {
            get {
                return ResourceManager.GetString("General_Class_Monk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladin.
        /// </summary>
        public static string General_Class_Paladin {
            get {
                return ResourceManager.GetString("General_Class_Paladin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranger.
        /// </summary>
        public static string General_Class_Ranger {
            get {
                return ResourceManager.GetString("General_Class_Ranger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue.
        /// </summary>
        public static string General_Class_Rogue {
            get {
                return ResourceManager.GetString("General_Class_Rogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorcerer.
        /// </summary>
        public static string General_Class_Sorcerer {
            get {
                return ResourceManager.GetString("General_Class_Sorcerer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warlock.
        /// </summary>
        public static string General_Class_Warlock {
            get {
                return ResourceManager.GetString("General_Class_Warlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        public static string General_Class_Wizard {
            get {
                return ResourceManager.GetString("General_Class_Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con.
        /// </summary>
        public static string General_Con {
            get {
                return ResourceManager.GetString("General_Con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution.
        /// </summary>
        public static string General_Constitution {
            get {
                return ResourceManager.GetString("General_Constitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fails.
        /// </summary>
        public static string General_DeathFails {
            get {
                return ResourceManager.GetString("General_DeathFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passes.
        /// </summary>
        public static string General_DeathSaves {
            get {
                return ResourceManager.GetString("General_DeathSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Throws.
        /// </summary>
        public static string General_DeathThrows {
            get {
                return ResourceManager.GetString("General_DeathThrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dex.
        /// </summary>
        public static string General_Dex {
            get {
                return ResourceManager.GetString("General_Dex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        public static string General_Dexterity {
            get {
                return ResourceManager.GetString("General_Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flaws.
        /// </summary>
        public static string General_Flaws {
            get {
                return ResourceManager.GetString("General_Flaws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glance Value.
        /// </summary>
        public static string General_GroupBox_GlanceValue {
            get {
                return ResourceManager.GetString("General_GroupBox_GlanceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personality.
        /// </summary>
        public static string General_GroupBox_Personality {
            get {
                return ResourceManager.GetString("General_GroupBox_Personality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statblock.
        /// </summary>
        public static string General_GroupBox_Stats {
            get {
                return ResourceManager.GetString("General_GroupBox_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Dice.
        /// </summary>
        public static string General_HitDice {
            get {
                return ResourceManager.GetString("General_HitDice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideals.
        /// </summary>
        public static string General_Ideals {
            get {
                return ResourceManager.GetString("General_Ideals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspiration.
        /// </summary>
        public static string General_Inspiration {
            get {
                return ResourceManager.GetString("General_Inspiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int.
        /// </summary>
        public static string General_Int {
            get {
                return ResourceManager.GetString("General_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        public static string General_Intelligence {
            get {
                return ResourceManager.GetString("General_Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string General_Languages {
            get {
                return ResourceManager.GetString("General_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lvl.
        /// </summary>
        public static string General_Lvl {
            get {
                return ResourceManager.GetString("General_Lvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof. Bonus.
        /// </summary>
        public static string General_PBonus {
            get {
                return ResourceManager.GetString("General_PBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profficiencies.
        /// </summary>
        public static string General_Profficiencies {
            get {
                return ResourceManager.GetString("General_Profficiencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string General_Race {
            get {
                return ResourceManager.GetString("General_Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Elf.
        /// </summary>
        public static string General_Race_DarkElf {
            get {
                return ResourceManager.GetString("General_Race_DarkElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragonborn.
        /// </summary>
        public static string General_Race_Dragonborn {
            get {
                return ResourceManager.GetString("General_Race_Dragonborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest Gnome.
        /// </summary>
        public static string General_Race_ForestGnome {
            get {
                return ResourceManager.GetString("General_Race_ForestGnome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-Elf.
        /// </summary>
        public static string General_Race_HalfElf {
            get {
                return ResourceManager.GetString("General_Race_HalfElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halfling.
        /// </summary>
        public static string General_Race_Halfling {
            get {
                return ResourceManager.GetString("General_Race_Halfling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-Orc.
        /// </summary>
        public static string General_Race_HalfOrc {
            get {
                return ResourceManager.GetString("General_Race_HalfOrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hill Dwarf.
        /// </summary>
        public static string General_Race_HillDwarf {
            get {
                return ResourceManager.GetString("General_Race_HillDwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        public static string General_Race_Human {
            get {
                return ResourceManager.GetString("General_Race_Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Variant.
        /// </summary>
        public static string General_Race_HumanVar {
            get {
                return ResourceManager.GetString("General_Race_HumanVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon Elf.
        /// </summary>
        public static string General_Race_MoonElf {
            get {
                return ResourceManager.GetString("General_Race_MoonElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain Dwarf.
        /// </summary>
        public static string General_Race_MountainDwarf {
            get {
                return ResourceManager.GetString("General_Race_MountainDwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock Gnome.
        /// </summary>
        public static string General_Race_RockGnome {
            get {
                return ResourceManager.GetString("General_Race_RockGnome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun Elf.
        /// </summary>
        public static string General_Race_SunElf {
            get {
                return ResourceManager.GetString("General_Race_SunElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiefling.
        /// </summary>
        public static string General_Race_Tiefling {
            get {
                return ResourceManager.GetString("General_Race_Tiefling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood Elf.
        /// </summary>
        public static string General_Race_WoodElf {
            get {
                return ResourceManager.GetString("General_Race_WoodElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves.
        /// </summary>
        public static string General_Saves {
            get {
                return ResourceManager.GetString("General_Saves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Dex] Acrobatics.
        /// </summary>
        public static string General_Skill_Acrobatics {
            get {
                return ResourceManager.GetString("General_Skill_Acrobatics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Wis] Animal Handling.
        /// </summary>
        public static string General_Skill_AH {
            get {
                return ResourceManager.GetString("General_Skill_AH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Int] Arcana.
        /// </summary>
        public static string General_Skill_Arcana {
            get {
                return ResourceManager.GetString("General_Skill_Arcana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Str] Athletics.
        /// </summary>
        public static string General_Skill_Athletics {
            get {
                return ResourceManager.GetString("General_Skill_Athletics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Cha] Deception.
        /// </summary>
        public static string General_Skill_Deception {
            get {
                return ResourceManager.GetString("General_Skill_Deception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Int] History.
        /// </summary>
        public static string General_Skill_History {
            get {
                return ResourceManager.GetString("General_Skill_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Wis] Insight.
        /// </summary>
        public static string General_Skill_Insight {
            get {
                return ResourceManager.GetString("General_Skill_Insight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Cha] Intimidation.
        /// </summary>
        public static string General_Skill_Intimidation {
            get {
                return ResourceManager.GetString("General_Skill_Intimidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Int] Investigation.
        /// </summary>
        public static string General_Skill_Investigation {
            get {
                return ResourceManager.GetString("General_Skill_Investigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Wis] Medicine.
        /// </summary>
        public static string General_Skill_Medicine {
            get {
                return ResourceManager.GetString("General_Skill_Medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Int] Nature.
        /// </summary>
        public static string General_Skill_Nature {
            get {
                return ResourceManager.GetString("General_Skill_Nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Wis] Perception.
        /// </summary>
        public static string General_Skill_Perception {
            get {
                return ResourceManager.GetString("General_Skill_Perception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Cha] Performance.
        /// </summary>
        public static string General_Skill_Performance {
            get {
                return ResourceManager.GetString("General_Skill_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Cha] Persuasion.
        /// </summary>
        public static string General_Skill_Persuasion {
            get {
                return ResourceManager.GetString("General_Skill_Persuasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Int] Religion.
        /// </summary>
        public static string General_Skill_Religion {
            get {
                return ResourceManager.GetString("General_Skill_Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Dex] Sleight of Hand.
        /// </summary>
        public static string General_Skill_SleightOfHand {
            get {
                return ResourceManager.GetString("General_Skill_SleightOfHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Dex] Stealth.
        /// </summary>
        public static string General_Skill_Stealth {
            get {
                return ResourceManager.GetString("General_Skill_Stealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Wis] Survival.
        /// </summary>
        public static string General_Skill_Survival {
            get {
                return ResourceManager.GetString("General_Skill_Survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string General_Skills {
            get {
                return ResourceManager.GetString("General_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string General_Speed {
            get {
                return ResourceManager.GetString("General_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Str.
        /// </summary>
        public static string General_Str {
            get {
                return ResourceManager.GetString("General_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string General_Strength {
            get {
                return ResourceManager.GetString("General_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traits.
        /// </summary>
        public static string General_Traits {
            get {
                return ResourceManager.GetString("General_Traits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wis.
        /// </summary>
        public static string General_Wis {
            get {
                return ResourceManager.GetString("General_Wis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisdom.
        /// </summary>
        public static string General_Wisdom {
            get {
                return ResourceManager.GetString("General_Wisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Generic_No {
            get {
                return ResourceManager.GetString("Generic_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Generic_OK {
            get {
                return ResourceManager.GetString("Generic_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An old or incompatible save file was loaded. Due to the way stat calculations were changed it is recommended to do a stat rebuild. Do the rebuild?.
        /// </summary>
        public static string Generic_OldSave_Pass1 {
            get {
                return ResourceManager.GetString("Generic_OldSave_Pass1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An old or incompatible save file was loaded. Due to general potential save partial or full incompatibility it is recommended to override the file. Save now?.
        /// </summary>
        public static string Generic_OldSave_Pass2 {
            get {
                return ResourceManager.GetString("Generic_OldSave_Pass2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old save file loaded.
        /// </summary>
        public static string Generic_OldSave_Title {
            get {
                return ResourceManager.GetString("Generic_OldSave_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t save the sheet to the previous location: {0}, {1}. Press OK to select a different file to save to. Press Cancel to cancel the save alltogether..
        /// </summary>
        public static string Generic_SaveError_Description {
            get {
                return ResourceManager.GetString("Generic_SaveError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t save the sheet!.
        /// </summary>
        public static string Generic_SaveError_Title {
            get {
                return ResourceManager.GetString("Generic_SaveError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Generic_Source {
            get {
                return ResourceManager.GetString("Generic_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes. Do you want to save the file before resetting it? Press Yes to save the file and reset it. Press No to discard all changes and reset it. Press Cancel to abort the operation.
        /// </summary>
        public static string Generic_Unsaved_Description {
            get {
                return ResourceManager.GetString("Generic_Unsaved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes exist!.
        /// </summary>
        public static string Generic_Unsaved_Title {
            get {
                return ResourceManager.GetString("Generic_Unsaved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wondrous.
        /// </summary>
        public static string Generic_Wondrous {
            get {
                return ResourceManager.GetString("Generic_Wondrous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Generic_Yes {
            get {
                return ResourceManager.GetString("Generic_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used 3rd party libraries.
        /// </summary>
        public static string Info_3rd {
            get {
                return ResourceManager.GetString("Info_3rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Info_Author {
            get {
                return ResourceManager.GetString("Info_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Info_Information {
            get {
                return ResourceManager.GetString("Info_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string Info_License {
            get {
                return ResourceManager.GetString("Info_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository link.
        /// </summary>
        public static string Info_Repo {
            get {
                return ResourceManager.GetString("Info_Repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Info_Version {
            get {
                return ResourceManager.GetString("Info_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Inventory_Backpack {
            get {
                return ResourceManager.GetString("Inventory_Backpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Inventory_Cash {
            get {
                return ResourceManager.GetString("Inventory_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP.
        /// </summary>
        public static string Inventory_CP {
            get {
                return ResourceManager.GetString("Inventory_CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EP.
        /// </summary>
        public static string Inventory_EP {
            get {
                return ResourceManager.GetString("Inventory_EP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string Inventory_Equip {
            get {
                return ResourceManager.GetString("Inventory_Equip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Inventory_Filter {
            get {
                return ResourceManager.GetString("Inventory_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP.
        /// </summary>
        public static string Inventory_GP {
            get {
                return ResourceManager.GetString("Inventory_GP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Results.
        /// </summary>
        public static string Inventory_InvertSort {
            get {
                return ResourceManager.GetString("Inventory_InvertSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PP.
        /// </summary>
        public static string Inventory_PP {
            get {
                return ResourceManager.GetString("Inventory_PP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rings.
        /// </summary>
        public static string Inventory_Rings {
            get {
                return ResourceManager.GetString("Inventory_Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Inventory_Sort_Amount {
            get {
                return ResourceManager.GetString("Inventory_Sort_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Inventory_Sort_Cost {
            get {
                return ResourceManager.GetString("Inventory_Sort_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        public static string Inventory_Sort_Cost_Total {
            get {
                return ResourceManager.GetString("Inventory_Sort_Cost_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Inventory_Sort_Name {
            get {
                return ResourceManager.GetString("Inventory_Sort_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarity.
        /// </summary>
        public static string Inventory_Sort_Rarity {
            get {
                return ResourceManager.GetString("Inventory_Sort_Rarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Inventory_Sort_Type {
            get {
                return ResourceManager.GetString("Inventory_Sort_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Inventory_Sort_Weight {
            get {
                return ResourceManager.GetString("Inventory_Sort_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Weight.
        /// </summary>
        public static string Inventory_Sort_Weight_Total {
            get {
                return ResourceManager.GetString("Inventory_Sort_Weight_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string Inventory_Sorting {
            get {
                return ResourceManager.GetString("Inventory_Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP.
        /// </summary>
        public static string Inventory_SP {
            get {
                return ResourceManager.GetString("Inventory_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Inventory_Weight {
            get {
                return ResourceManager.GetString("Inventory_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filters.
        /// </summary>
        public static string ItemIndex_Apply {
            get {
                return ResourceManager.GetString("ItemIndex_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ItemIndex_Name {
            get {
                return ResourceManager.GetString("ItemIndex_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammunition.
        /// </summary>
        public static string ItemIndex_Prop_Ammo {
            get {
                return ResourceManager.GetString("ItemIndex_Prop_Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finesse.
        /// </summary>
        public static string ItemIndex_Prop_Finesse {
            get {
                return ResourceManager.GetString("ItemIndex_Prop_Finesse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy.
        /// </summary>
        public static string ItemIndex_Prop_Heavy {
            get {
                return ResourceManager.GetString("ItemIndex_Prop_Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ItemIndex_Prop_Light {
            get {
                return ResourceManager.GetString("ItemIndex_Prop_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string ItemIndex_Prop_Loading {
            get {
                return ResourceManager.GetString("ItemIndex_Prop_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string ItemIndex_Prop_Range {
            get {
                return ResourceManager.GetString("ItemIndex_Prop_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach.
        /// </summary>
        public static string ItemIndex_Prop_Reach {
            get {
                return ResourceManager.GetString("ItemIndex_Prop_Reach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrown.
        /// </summary>
        public static string ItemIndex_Prop_Thrown {
            get {
                return ResourceManager.GetString("ItemIndex_Prop_Thrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Handed.
        /// </summary>
        public static string ItemIndex_Prop_TwoHanded {
            get {
                return ResourceManager.GetString("ItemIndex_Prop_TwoHanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versatile.
        /// </summary>
        public static string ItemIndex_Prop_Versatile {
            get {
                return ResourceManager.GetString("ItemIndex_Prop_Versatile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Filtering.
        /// </summary>
        public static string ItemIndex_Properties {
            get {
                return ResourceManager.GetString("ItemIndex_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string ItemIndex_Properties2 {
            get {
                return ResourceManager.GetString("ItemIndex_Properties2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarity.
        /// </summary>
        public static string ItemIndex_Rarity {
            get {
                return ResourceManager.GetString("ItemIndex_Rarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string ItemIndex_Rarity_Common {
            get {
                return ResourceManager.GetString("ItemIndex_Rarity_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary.
        /// </summary>
        public static string ItemIndex_Rarity_Legendary {
            get {
                return ResourceManager.GetString("ItemIndex_Rarity_Legendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        public static string ItemIndex_Rarity_Rare {
            get {
                return ResourceManager.GetString("ItemIndex_Rarity_Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommon.
        /// </summary>
        public static string ItemIndex_Rarity_Uncommon {
            get {
                return ResourceManager.GetString("ItemIndex_Rarity_Uncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Rare.
        /// </summary>
        public static string ItemIndex_Rarity_VeryRare {
            get {
                return ResourceManager.GetString("ItemIndex_Rarity_VeryRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering.
        /// </summary>
        public static string ItemIndex_Sorting {
            get {
                return ResourceManager.GetString("ItemIndex_Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Filtering.
        /// </summary>
        public static string ItemIndex_Types {
            get {
                return ResourceManager.GetString("ItemIndex_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the types to include
        ///Separate multiple types by a new line.
        /// </summary>
        public static string ItemIndex_Types_Desc {
            get {
                return ResourceManager.GetString("ItemIndex_Types_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wondrous Only.
        /// </summary>
        public static string ItemIndex_WondrousOnly {
            get {
                return ResourceManager.GetString("ItemIndex_WondrousOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainMenu_About {
            get {
                return ResourceManager.GetString("MainMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        public static string MainMenu_CheckForUpdates {
            get {
                return ResourceManager.GetString("MainMenu_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MainMenu_Edit {
            get {
                return ResourceManager.GetString("MainMenu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MainMenu_Exit {
            get {
                return ResourceManager.GetString("MainMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainMenu_File {
            get {
                return ResourceManager.GetString("MainMenu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        public static string MainMenu_File_New {
            get {
                return ResourceManager.GetString("MainMenu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Script....
        /// </summary>
        public static string MainMenu_File_New_FromScript {
            get {
                return ResourceManager.GetString("MainMenu_File_New_FromScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank Sheet.
        /// </summary>
        public static string MainMenu_File_New_New {
            get {
                return ResourceManager.GetString("MainMenu_File_New_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MainMenu_Info {
            get {
                return ResourceManager.GetString("MainMenu_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MainMenu_Open {
            get {
                return ResourceManager.GetString("MainMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roadmap.
        /// </summary>
        public static string MainMenu_Roadmap {
            get {
                return ResourceManager.GetString("MainMenu_Roadmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MainMenu_Save {
            get {
                return ResourceManager.GetString("MainMenu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string MainMenu_SaveAs {
            get {
                return ResourceManager.GetString("MainMenu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting.
        /// </summary>
        public static string MainMenu_Scripting {
            get {
                return ResourceManager.GetString("MainMenu_Scripting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MainMenu_View {
            get {
                return ResourceManager.GetString("MainMenu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string R20_Actions {
            get {
                return ResourceManager.GetString("R20_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Roll.
        /// </summary>
        public static string R20_AdvancedRoll {
            get {
                return ResourceManager.GetString("R20_AdvancedRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As multiple rolls.
        /// </summary>
        public static string R20_AsMulRolls {
            get {
                return ResourceManager.GetString("R20_AsMulRolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma Save.
        /// </summary>
        public static string R20_ChaSave {
            get {
                return ResourceManager.GetString("R20_ChaSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution Save.
        /// </summary>
        public static string R20_ConSave {
            get {
                return ResourceManager.GetString("R20_ConSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Client.
        /// </summary>
        public static string R20_CopyClient {
            get {
                return ResourceManager.GetString("R20_CopyClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity Save.
        /// </summary>
        public static string R20_DexSave {
            get {
                return ResourceManager.GetString("R20_DexSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence Save.
        /// </summary>
        public static string R20_IntSave {
            get {
                return ResourceManager.GetString("R20_IntSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string R20_Log {
            get {
                return ResourceManager.GetString("R20_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolls.
        /// </summary>
        public static string R20_Rolls {
            get {
                return ResourceManager.GetString("R20_Rolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Help:
        ///Press the &quot;Start server&quot; button first. This will copy the client to your clipboard. 
        ///Open the browser window, navigate to the game, make sure the game is running, press F12 on your keyboard, select the Console tab and press Ctrl+V into the console.
        ///On certain browsers you may need to do more actions..
        /// </summary>
        public static string R20_ServerHelp {
            get {
                return ResourceManager.GetString("R20_ServerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerPanel.
        /// </summary>
        public static string R20_ServerPanel {
            get {
                return ResourceManager.GetString("R20_ServerPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Status.
        /// </summary>
        public static string R20_ServerStatus {
            get {
                return ResourceManager.GetString("R20_ServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills And Saves.
        /// </summary>
        public static string R20_SkillsAndSaves {
            get {
                return ResourceManager.GetString("R20_SkillsAndSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Lost.
        /// </summary>
        public static string R20_SS_ConLost {
            get {
                return ResourceManager.GetString("R20_SS_ConLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Estabilished.
        /// </summary>
        public static string R20_SS_Connection {
            get {
                return ResourceManager.GetString("R20_SS_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening.
        /// </summary>
        public static string R20_SS_Listening {
            get {
                return ResourceManager.GetString("R20_SS_Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        public static string R20_SS_NotStarted {
            get {
                return ResourceManager.GetString("R20_SS_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Server.
        /// </summary>
        public static string R20_StartServer {
            get {
                return ResourceManager.GetString("R20_StartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Server.
        /// </summary>
        public static string R20_StopServer {
            get {
                return ResourceManager.GetString("R20_StopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength Save.
        /// </summary>
        public static string R20_StrSave {
            get {
                return ResourceManager.GetString("R20_StrSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisdom Save.
        /// </summary>
        public static string R20_WisSave {
            get {
                return ResourceManager.GetString("R20_WisSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Attack Bonus.
        /// </summary>
        public static string Spellbook_AttackBonus {
            get {
                return ResourceManager.GetString("Spellbook_AttackBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering.
        /// </summary>
        public static string Spellbook_Filtering {
            get {
                return ResourceManager.GetString("Spellbook_Filtering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantrips.
        /// </summary>
        public static string Spellbook_lv0 {
            get {
                return ResourceManager.GetString("Spellbook_lv0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1.
        /// </summary>
        public static string Spellbook_lv1 {
            get {
                return ResourceManager.GetString("Spellbook_lv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 2.
        /// </summary>
        public static string Spellbook_lv2 {
            get {
                return ResourceManager.GetString("Spellbook_lv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3.
        /// </summary>
        public static string Spellbook_lv3 {
            get {
                return ResourceManager.GetString("Spellbook_lv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 4.
        /// </summary>
        public static string Spellbook_lv4 {
            get {
                return ResourceManager.GetString("Spellbook_lv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 5.
        /// </summary>
        public static string Spellbook_lv5 {
            get {
                return ResourceManager.GetString("Spellbook_lv5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 6.
        /// </summary>
        public static string Spellbook_lv6 {
            get {
                return ResourceManager.GetString("Spellbook_lv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 7.
        /// </summary>
        public static string Spellbook_lv7 {
            get {
                return ResourceManager.GetString("Spellbook_lv7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 8.
        /// </summary>
        public static string Spellbook_lv8 {
            get {
                return ResourceManager.GetString("Spellbook_lv8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 9.
        /// </summary>
        public static string Spellbook_lv9 {
            get {
                return ResourceManager.GetString("Spellbook_lv9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Spells.
        /// </summary>
        public static string Spellbook_MaxSpells {
            get {
                return ResourceManager.GetString("Spellbook_MaxSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell save DC.
        /// </summary>
        public static string Spellbook_SaveDC {
            get {
                return ResourceManager.GetString("Spellbook_SaveDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slots.
        /// </summary>
        public static string Spellbook_Slots {
            get {
                return ResourceManager.GetString("Spellbook_Slots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellcasting Ability.
        /// </summary>
        public static string Spellbook_SpellcastingAbility {
            get {
                return ResourceManager.GetString("Spellbook_SpellcastingAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filters.
        /// </summary>
        public static string SpellIndex_ApplyFilters {
            get {
                return ResourceManager.GetString("SpellIndex_ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bard.
        /// </summary>
        public static string SpellIndex_Class_Bard {
            get {
                return ResourceManager.GetString("SpellIndex_Class_Bard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleric.
        /// </summary>
        public static string SpellIndex_Class_Cleric {
            get {
                return ResourceManager.GetString("SpellIndex_Class_Cleric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druid.
        /// </summary>
        public static string SpellIndex_Class_Druid {
            get {
                return ResourceManager.GetString("SpellIndex_Class_Druid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladin.
        /// </summary>
        public static string SpellIndex_Class_Paladin {
            get {
                return ResourceManager.GetString("SpellIndex_Class_Paladin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranger.
        /// </summary>
        public static string SpellIndex_Class_Ranger {
            get {
                return ResourceManager.GetString("SpellIndex_Class_Ranger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorcerer.
        /// </summary>
        public static string SpellIndex_Class_Sorcerer {
            get {
                return ResourceManager.GetString("SpellIndex_Class_Sorcerer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warlock.
        /// </summary>
        public static string SpellIndex_Class_Warlock {
            get {
                return ResourceManager.GetString("SpellIndex_Class_Warlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        public static string SpellIndex_Class_Wizard {
            get {
                return ResourceManager.GetString("SpellIndex_Class_Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string SpellIndex_Classes {
            get {
                return ResourceManager.GetString("SpellIndex_Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering.
        /// </summary>
        public static string SpellIndex_Filtering {
            get {
                return ResourceManager.GetString("SpellIndex_Filtering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string SpellIndex_Level {
            get {
                return ResourceManager.GetString("SpellIndex_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SpellIndex_Name {
            get {
                return ResourceManager.GetString("SpellIndex_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ritual Only.
        /// </summary>
        public static string SpellIndex_Ritual {
            get {
                return ResourceManager.GetString("SpellIndex_Ritual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abjuration.
        /// </summary>
        public static string SpellIndex_School_Abjuration {
            get {
                return ResourceManager.GetString("SpellIndex_School_Abjuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conjuration.
        /// </summary>
        public static string SpellIndex_School_Conjuration {
            get {
                return ResourceManager.GetString("SpellIndex_School_Conjuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divination.
        /// </summary>
        public static string SpellIndex_School_Divination {
            get {
                return ResourceManager.GetString("SpellIndex_School_Divination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enchantment.
        /// </summary>
        public static string SpellIndex_School_Enchantment {
            get {
                return ResourceManager.GetString("SpellIndex_School_Enchantment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evocation.
        /// </summary>
        public static string SpellIndex_School_Evocation {
            get {
                return ResourceManager.GetString("SpellIndex_School_Evocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illusion.
        /// </summary>
        public static string SpellIndex_School_Illusion {
            get {
                return ResourceManager.GetString("SpellIndex_School_Illusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necromancy.
        /// </summary>
        public static string SpellIndex_School_Necromancy {
            get {
                return ResourceManager.GetString("SpellIndex_School_Necromancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmutation.
        /// </summary>
        public static string SpellIndex_School_Transmutation {
            get {
                return ResourceManager.GetString("SpellIndex_School_Transmutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schools.
        /// </summary>
        public static string SpellIndex_Schools {
            get {
                return ResourceManager.GetString("SpellIndex_Schools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemental Evil.
        /// </summary>
        public static string SpellIndex_Source_EE {
            get {
                return ResourceManager.GetString("SpellIndex_Source_EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homebrew.
        /// </summary>
        public static string SpellIndex_Source_HB {
            get {
                return ResourceManager.GetString("SpellIndex_Source_HB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players Handbook.
        /// </summary>
        public static string SpellIndex_Source_PHB {
            get {
                return ResourceManager.GetString("SpellIndex_Source_PHB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sword Coast Adv. Guide.
        /// </summary>
        public static string SpellIndex_Source_SCAG {
            get {
                return ResourceManager.GetString("SpellIndex_Source_SCAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprouting Chaos.
        /// </summary>
        public static string SpellIndex_Source_SCPC {
            get {
                return ResourceManager.GetString("SpellIndex_Source_SCPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xanathars Guide To Everything.
        /// </summary>
        public static string SpellIndex_Source_XGTE {
            get {
                return ResourceManager.GetString("SpellIndex_Source_XGTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        public static string SpellIndex_Sources {
            get {
                return ResourceManager.GetString("SpellIndex_Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        public static string Tab_Extras {
            get {
                return ResourceManager.GetString("Tab_Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Tab_General {
            get {
                return ResourceManager.GetString("Tab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Tab_Inventory {
            get {
                return ResourceManager.GetString("Tab_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DnD5e Item Index.
        /// </summary>
        public static string Tab_InventoryCodex {
            get {
                return ResourceManager.GetString("Tab_InventoryCodex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellbook.
        /// </summary>
        public static string Tab_Spellbook {
            get {
                return ResourceManager.GetString("Tab_Spellbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DnD5e Spell Index.
        /// </summary>
        public static string Tab_SpellCodex {
            get {
                return ResourceManager.GetString("Tab_SpellCodex", resourceCulture);
            }
        }
    }
}
